version: '2.8'
services:
    flask-app:
        build: .
        image: flask-app-lab4
        container_name: flask-app
        ports:
            - "5000:5000"
        volumes:
            -   .:/code

